#! /bin/bash

absolute(){
file=` basename $1 `
#echo $file
cpath=${2#*${file}}
fpath=$1$cpath
#echo $fpath
echo "adb push $2 $fpath"
adb push $2 $fpath
return 0
}
# $1 rpath $2 file
relative(){
echo relative
find . -name $2 | awk '{ print NR  $1 }'
read -p "the correct path number " num
read lpath <<< ` find ./ -name $2 | awk "NR==$num "'{print $1}'  `
if [ -z $lpath ];
then
echo "404 not found"
else
fpath=`dirname $RPATH`/$lpath
echo "adb push $lpath $fpath "
adb push $lpath $fpath
fi
}


if [ -z $RPATH ];
then
read -p "input the remote path " RPATH
fi

if [ -z $1 ];
then 
read -p "input the file name " fname
relative $RPATH $fname
elif [[ $1 =~ "/" ]]; 
then
echo "absolutional path"
absolute $RPATH $1
else
relative $RPATH $1
fi



