#! /bin/bash
if [ -z $RPATH ];
then
read -p "input the remote path " RPATH
fi
#echo $rpath
if [ -z $1 ];
then 
read -p "input the file name " fname
else
fname=$1
fi
#echo "filename "$fname
find . -name $fname | awk '{ print NR  $1 }'
read -p "the correct path number " num
# find ./ -name $fname | awk "NR==$num {print $1}" | (read lpath) 
read lpath <<< ` find ./ -name $fname | awk "NR==$num "'{print $1}'  `
echo $lpath
if [ -z $lpath ];
then
echo "404 not found"
else
fpath=$RPATH"/"$lpath
echo "adb push $lpath $fpath "
MSYS_NO_PATHCONV=1 adb push $lpath $fpath
fi
